export default [
    {
        id: 1,
        name: 'Beatriz Farias',
        email: 'bia.farias@gmail.com',
        avatar: 'https://i.pravatar.cc/150?img=31',
        age: 35,
        genero: 'F',
    },
    {
        id: 2,
        name: 'Julia Santos',
        email: 'jujusantos123@hotmail.com',
        avatar: 'https://i.pravatar.cc/150?img=32',
        age: 15,
        genero: 'F',
    },
    {
        id: 3,
        name: 'Pedro Mendonça',
        email: 'eu@pedro.com',
        avatar: 'https://i.pravatar.cc/150?img=33',
        age: 56,
        genero: 'M',
    },
    {
        id: 4,
        name: 'Julia Shinoda',
        email: 'julia.shinoda@japao.com',
        avatar: 'https://i.pravatar.cc/150?img=34',
        age: 5,
        genero: 'F',
    },
    {
        id: 5,
        name: 'Andrezza Shinoda',
        email: 'andrezza99@hotmail.com',
        avatar: 'https://i.pravatar.cc/150?img=35',
        age: 78,
        genero: 'F',
    },
    {
        id: 6,
        name: 'Sara Maria',
        email: 'saramaria@gmail.com',
        avatar: 'https://i.pravatar.cc/150?img=36',
        age: 18,
        genero: 'F',
    },
    {
        id: 7,
        name: 'Edna Sousa',
        email: 'edna21@yahoo.com.br',
        avatar: 'https://i.pravatar.cc/150?img=37',
        age: 24,
        genero: 'F',
    },
];